# Generated by Django 3.2.9 on 2025-01-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='photoes/avatars/avatar.png', upload_to='photoes/avatars'),
        ),
    ]
