# Generated by Django 3.2.9 on 2025-01-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
